export const ACTION_MOTION_SPECS = Object.freeze({
  'waving-real': { poseFile: 'waving-real.png', motion: 'wave' },
  singing: { poseFile: 'singing.png', motion: 'sing' },
  sleeping: { poseFile: 'sleeping.png', motion: 'sleep' },
  waking: { poseFile: 'waking.png', motion: 'wake' },
  // 待机系统一使用 idle_base.png（标准立绘归一化），保证与所有动作视频的
  // 稳定几何（脚底 y=403、中心 x=192）一致，图层切换零跳变。
  idle_breath: { poseFile: 'idle_base.png', motion: 'breath' },
  idle_blink: { poseFile: 'idle_base.png', motion: 'blink' },
  idle_stare: { poseFile: 'idle_base.png', motion: 'stare' },
  transition_settle: { poseFile: 'idle_base.png', motion: 'settle' },
  emo_happy: { poseFile: 'emo_happy.png', motion: 'happy' },
  emo_shy: { poseFile: 'emo_shy.png', motion: 'shy' },
  emo_angry: { poseFile: 'emo_angry.png', motion: 'angry' },
  emo_sleepy: { poseFile: 'emo_sleepy.png', motion: 'sleepy' },
  emo_sad: { poseFile: 'emo_sad.png', motion: 'sad' },
  emo_excited: { poseFile: 'emo_excited.png', motion: 'excited' },
  emo_surprise: { poseFile: 'emo_surprise.png', motion: 'surprise' },
  emo_aggrieved: { poseFile: 'emo_aggrieved.png', motion: 'aggrieved' },
  act_stretch: { poseFile: 'act_stretch.png', motion: 'stretch' },
  act_scratch: { poseFile: 'act_scratch.png', motion: 'scratch' },
  act_yawn: { poseFile: 'act_yawn.png', motion: 'yawn' },
  act_chin: { poseFile: 'act_chin.png', motion: 'chin' },
  act_spin: { poseFiles: ['act_spin-01.png', 'act_spin-02.png', 'act_spin-03.png'], motion: 'sequence' },
  act_flip_hair: { poseFiles: ['act_flip_hair-01.png', 'act_flip_hair-02.png'], motion: 'sequence' },
  act_table: { poseFiles: ['act_table-01.png', 'act_table-02.png'], motion: 'sequence' },
  act_lookaround: { poseFiles: ['act_lookaround-01.png', 'act_lookaround-02.png'], motion: 'sequence' },
  act_roll: { poseFiles: ['act_roll-01.png', 'act_roll-02.png', 'act_roll-03.png', 'act_roll-04.png'], motion: 'sequence' },
  act_hop: { poseFiles: ['act_hop-01.png', 'act_hop-02.png', 'act_hop-03.png'], motion: 'sequence' },
  act_rub_eye: { poseFile: 'act_rub_eye-01.png', motion: 'sequence' },
  act_sneeze: { poseFiles: ['act_sneeze-01.png', 'act_sneeze-02.png', 'act_sneeze-03.png'], motion: 'sequence' },
  act_dance: { poseFiles: ['act_dance-01.png', 'act_dance-02.png', 'act_dance-03.png'], motion: 'sequence' },
  act_work: { poseFiles: ['act_work-01.png', 'act_work-02.png'], motion: 'sequence' },
  act_ink: { poseFiles: ['act_ink-01.png', 'act_ink-02.png', 'act_ink-03.png'], motion: 'sequence' },
  act_firework: { poseFiles: ['act_firework-01.png', 'act_firework-02.png', 'act_firework-03.png'], motion: 'sequence' },
  act_intro: { poseFiles: ['act_intro-01.png', 'act_intro-02.png'], motion: 'sequence' },
  act_joke: { poseFiles: ['act_joke-01.png', 'act_joke-02.png', 'act_joke-03.png', 'act_joke-04.png'], motion: 'sequence' },
  gift_thanks: { poseFiles: ['gift_thanks-01.png', 'gift_thanks-02.png'], motion: 'sequence' },
  special_hourly: { poseFile: 'special_hourly-01.png', motion: 'sequence' },
  special_lottery: { poseFiles: ['special_lottery-01.png', 'special_lottery-02.png', 'special_lottery-03.png'], motion: 'sequence' },
  state_move: { poseFiles: ['state_move-01.png', 'state_move-02.png', 'state_move-01.png'], motion: 'sequence' },
  state_observe: { poseFiles: ['state_observe-01.png', 'state_observe-02.png', 'state_observe-03.png', 'state_observe-02.png', 'state_observe-01.png'], motion: 'sequence' },
  state_talking: { poseFiles: ['state_talking-01.png', 'state_talking-02.png', 'state_talking-01.png'], motion: 'sequence', poseMix: { from: 0.3, to: 0.9 } },
  gift_sc: { poseFile: 'gift_sc-01.png', motion: 'sequence' },
  gift_guard: { poseFile: 'gift_guard-01.png', motion: 'sequence' },
})

export const RENDER_READY_ACTION_IDS = Object.freeze([
  'waving-real',
  'singing',
  'sleeping',
  'waking',
  'idle_breath',
  'idle_blink',
  'idle_stare',
  'transition_settle',
  'emo_happy',
  'emo_shy',
  'emo_angry',
  'emo_sleepy',
  'emo_sad',
  'emo_excited',
  'emo_surprise',
  'emo_aggrieved',
  'act_stretch',
  'act_scratch',
  'act_yawn',
  'act_chin',
  'act_spin',
  'act_flip_hair',
  'act_table',
  'act_lookaround',
  'act_roll',
  'act_hop',
  'act_rub_eye',
  'act_sneeze',
  'act_dance',
  'act_work',
  'act_ink',
  'act_firework',
  'act_intro',
  'act_joke',
  'gift_thanks',
  'special_hourly',
  'special_lottery',
  'state_move',
  'state_observe',
  'state_talking',
  'gift_sc',
  'gift_guard',
])

export function getActionMotionSpec(actionId) {
  return Object.prototype.hasOwnProperty.call(ACTION_MOTION_SPECS, actionId)
    ? ACTION_MOTION_SPECS[actionId]
    : null
}
