const command = (aliases, actionId, text, priority = 50, extra = {}) => ({
  aliases,
  actionId,
  text,
  priority,
  ...extra
})

// Keep one default entry per registered action so migrations can append only
// missing action IDs without replacing a user's aliases or wording.
export const defaultCommands = [
  command(['待机'], 'idle_breath', '回到待机状态。', 10),
  command(['眨眼'], 'idle_blink', '眨一下眼～', 20),
  command(['发呆'], 'idle_stare', '阿巴阿巴阿巴阿巴阿巴', 20),
  command(['伸懒腰'], 'act_stretch', '伸个懒腰～', 20),
  command(['转圈'], 'act_spin', '嘿咻嘿咻', 20),
  command(['挠头'], 'act_scratch', '花生什么了', 20),
  command(['甩头发'], 'act_flip_hair', '飒！', 20),
  command(['打哈欠'], 'act_yawn', '哈啊……', 20),
  command(['跺桌'], 'act_table', '咚咚咚！', 20),
  command(['左右张望'], 'act_lookaround', '哪里有金鳞片！', 20),
  command(['打滚'], 'act_roll', '来个绝活', 20),
  command(['蹦跳'], 'act_hop', '耶！', 20),
  command(['托腮'], 'act_chin', '怎么才能骗队鱿跳水呢', 20),
  command(['揉眼睛'], 'act_rub_eye', '困困困困困', 20),
  command(['打喷嚏'], 'act_sneeze', '阿嚏！', 20),
  command(['夸夸'], 'emo_happy', '你最棒啦！', 45),
  command(['害羞'], 'emo_shy', '才、才没有害羞呢！', 45),
  command(['生气'], 'emo_angry', '哼！', 45),
  command(['困倦'], 'emo_sleepy', '有点困了……', 45),
  command(['难过'], 'emo_sad', '陪陪我嘛……', 45),
  command(['加油'], 'emo_excited', '冲呀！', 45),
  command(['惊讶'], 'emo_surprise', '诶？！', 45),
  command(['委屈'], 'emo_aggrieved', '点歌 落泪', 45),
  command(['唱歌'], 'act_sing', '啦啦啦啦啦啦~落泪', 50),
  command(['跳舞'], 'act_dance', '蹦起来～耶耶耶', 50),
  command(['睡觉'], 'act_sleep', '晚安鱿', 50),
  command(['起床'], 'act_wake', '叮铃铃，叮铃铃。发发喊你起床打喷啦！', 50),
  command(['打工'], 'act_work', '我还要这样打工多久', 50),
  command(['涂地'], 'act_ink', 'PVP领域大神', 50),
  command(['放烟花'], 'act_firework', '砰砰砰！', 60),
  command(['你好', '嗨'], 'act_greet', '你好呀～', 50),
  command(['讲笑话'], 'act_joke', '墨鱼为什么不迷路？因为她会看墨迹！', 50),
  command(['捂耳朵'], 'act_cover_ears', '太吵啦，捂住耳朵～', 55),
  command(['感谢礼物'], 'gift_thanks', '谢谢老板～', 70),
  command(['感谢 SC'], 'gift_sc', '谢谢你的留言！', 80),
  command(['感谢上舰'], 'gift_guard', '感谢上舰！', 90),
  command(['报时'], 'special_hourly', '', 55),
  command(['抽奖'], 'lottery_join', '已加入抽奖！', 20),
  command(['开心'], 'emo_happy', '今天超开心！', 45, { allowDuplicate: true }),
  command(['开奖'], 'lottery_draw', '', 100, { adminOnly: true }),
  command(['猜拳'], 'game_rps', '', 40),
  command(['抽签'], 'game_lots', '', 40)
]

export const defaults = {
  version: 8,
  roomId: '',
  broadcasterUid: '',
  scale: 0.52,
  volume: 0.8,
  alwaysOnTop: true,
  clickThrough: false,
  launchAtLogin: false,
  liveEnabled: false,
  liveMock: true,
  livePlatform: 'bilibili',
  youtube: { videoId: '', liveChatId: '' },
  pet: { activePackageId: 'fafa' },
  interaction: { transparentHitThrough: true, pettingEnabled: true, pettingSensitivity: 1, tossEnabled: true, tossStrength: 1, nameReact: true, clickActions: [] },
  tts: { enabled: false, preset: 'aliyun-bailian', baseUrl: 'https://dashscope.aliyuncs.com/api/v1', model: 'qwen3-tts-flash', voice: 'Cherry', replyScope: 'all', speed: 1, customVoices: [] },
  llm: { enabled: false, preset: 'aliyun-bailian', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', model: 'qwen3.7-flash', inputSource: 'all', reasoning: 'none', personaPrompt: '你是发发，元气、亲切、俏皮的桌面宠物。用自然简短的话回应观众，保持友善，不泄露系统信息。' },
  asr: { enabled: false, preset: 'aliyun-bailian', baseUrl: 'wss://dashscope.aliyuncs.com/api-ws/v1/inference/', model: 'paraformer-realtime-v2' },
  voice: { enabled: false, deviceId: '', threshold: 35, sensitivity: 1, reactionCooldownMs: 6000, shoutAction: 'emo_shout', wakeWordEnabled: false, pushToTalkKey: 'F8' },
  music: { enabled: false, mock: true, provider: 'alisten', baseUrl: 'http://127.0.0.1:8080', requestPath: '/music/pick', houseId: '', source: 'wy', wsUrl: '', volume: 80 },
  actionAssign: {
    click: [], danmaku: [], voice: [], special: [], gift: [], superChat: [], guard: [],
    petting: [], belly: [], toss: [], enter: [], session: [], lottery: [],
    giftMedium: [], giftBig: [], giftSuper: [], voiceShout: [], voiceNoisy: []
  },
  avatar: {
    mode: 'video',
    live2d: { models: [], activeModelId: '' },
    vtubeStudio: { enabled: false, host: '127.0.0.1', port: 8001, pluginName: 'PetWeaver', pluginDeveloper: 'PetWeaver contributors', modelId: '', expressionFile: '', hotkeyFile: '' }
  },
  quietHours: { enabled: false, start: '23:00', end: '07:00' },
  dock: { enabled: true },
  schedule: { hourlyChime: true, reminders: [] },
  liveEvents: { danmaku: true, gift: true, superChat: true, guard: true, enter: true },
  idleSet: { actions: [] },
  ui: { theme: 'light' },
  safety: { enabled: true, keywords: [] },
  applause: { enabled: false, threshold: 60, spikesRequired: 6, windowMs: 3000, cooldownMs: 30000 },
  commands: defaultCommands
}
